// Generated by gencpp from file dishwasher_action/DishwasherGoal.msg
// DO NOT EDIT!


#ifndef DISHWASHER_ACTION_MESSAGE_DISHWASHERGOAL_H
#define DISHWASHER_ACTION_MESSAGE_DISHWASHERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dishwasher_action
{
template <class ContainerAllocator>
struct DishwasherGoal_
{
  typedef DishwasherGoal_<ContainerAllocator> Type;

  DishwasherGoal_()
    : dirtyDishes(0)  {
    }
  DishwasherGoal_(const ContainerAllocator& _alloc)
    : dirtyDishes(0)  {
  (void)_alloc;
    }



   typedef int32_t _dirtyDishes_type;
  _dirtyDishes_type dirtyDishes;





  typedef boost::shared_ptr< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DishwasherGoal_

typedef ::dishwasher_action::DishwasherGoal_<std::allocator<void> > DishwasherGoal;

typedef boost::shared_ptr< ::dishwasher_action::DishwasherGoal > DishwasherGoalPtr;
typedef boost::shared_ptr< ::dishwasher_action::DishwasherGoal const> DishwasherGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dishwasher_action::DishwasherGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dishwasher_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'dishwasher_action': ['/home/koa/Desktop/ConcordiaRobotics/robotics-prototype/robot/demos/RosAction/devel/share/dishwasher_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11b004445e03767b789ca06b8b13193d";
  }

  static const char* value(const ::dishwasher_action::DishwasherGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11b004445e03767bULL;
  static const uint64_t static_value2 = 0x789ca06b8b13193dULL;
};

template<class ContainerAllocator>
struct DataType< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dishwasher_action/DishwasherGoal";
  }

  static const char* value(const ::dishwasher_action::DishwasherGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 dirtyDishes\n\
";
  }

  static const char* value(const ::dishwasher_action::DishwasherGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dirtyDishes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DishwasherGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dishwasher_action::DishwasherGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dishwasher_action::DishwasherGoal_<ContainerAllocator>& v)
  {
    s << indent << "dirtyDishes: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dirtyDishes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISHWASHER_ACTION_MESSAGE_DISHWASHERGOAL_H
