// Generated by gencpp from file dishwasher_action/DishwasherResult.msg
// DO NOT EDIT!


#ifndef DISHWASHER_ACTION_MESSAGE_DISHWASHERRESULT_H
#define DISHWASHER_ACTION_MESSAGE_DISHWASHERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dishwasher_action
{
template <class ContainerAllocator>
struct DishwasherResult_
{
  typedef DishwasherResult_<ContainerAllocator> Type;

  DishwasherResult_()
    : dishesWashed()  {
    }
  DishwasherResult_(const ContainerAllocator& _alloc)
    : dishesWashed(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dishesWashed_type;
  _dishesWashed_type dishesWashed;





  typedef boost::shared_ptr< ::dishwasher_action::DishwasherResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dishwasher_action::DishwasherResult_<ContainerAllocator> const> ConstPtr;

}; // struct DishwasherResult_

typedef ::dishwasher_action::DishwasherResult_<std::allocator<void> > DishwasherResult;

typedef boost::shared_ptr< ::dishwasher_action::DishwasherResult > DishwasherResultPtr;
typedef boost::shared_ptr< ::dishwasher_action::DishwasherResult const> DishwasherResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dishwasher_action::DishwasherResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dishwasher_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'dishwasher_action': ['/home/koa/Desktop/ConcordiaRobotics/robotics-prototype/robot/demos/RosAction/devel/share/dishwasher_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dishwasher_action::DishwasherResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dishwasher_action::DishwasherResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dishwasher_action::DishwasherResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f0b089f3078e2af93fb747be1fd2495";
  }

  static const char* value(const ::dishwasher_action::DishwasherResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f0b089f3078e2afULL;
  static const uint64_t static_value2 = 0x93fb747be1fd2495ULL;
};

template<class ContainerAllocator>
struct DataType< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dishwasher_action/DishwasherResult";
  }

  static const char* value(const ::dishwasher_action::DishwasherResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
string dishesWashed\n\
";
  }

  static const char* value(const ::dishwasher_action::DishwasherResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dishesWashed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DishwasherResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dishwasher_action::DishwasherResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dishwasher_action::DishwasherResult_<ContainerAllocator>& v)
  {
    s << indent << "dishesWashed: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dishesWashed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISHWASHER_ACTION_MESSAGE_DISHWASHERRESULT_H
