// Generated by gencpp from file dishwasher_action/DishwasherFeedback.msg
// DO NOT EDIT!


#ifndef DISHWASHER_ACTION_MESSAGE_DISHWASHERFEEDBACK_H
#define DISHWASHER_ACTION_MESSAGE_DISHWASHERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dishwasher_action
{
template <class ContainerAllocator>
struct DishwasherFeedback_
{
  typedef DishwasherFeedback_<ContainerAllocator> Type;

  DishwasherFeedback_()
    : percentComplete(0.0)  {
    }
  DishwasherFeedback_(const ContainerAllocator& _alloc)
    : percentComplete(0.0)  {
  (void)_alloc;
    }



   typedef float _percentComplete_type;
  _percentComplete_type percentComplete;





  typedef boost::shared_ptr< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DishwasherFeedback_

typedef ::dishwasher_action::DishwasherFeedback_<std::allocator<void> > DishwasherFeedback;

typedef boost::shared_ptr< ::dishwasher_action::DishwasherFeedback > DishwasherFeedbackPtr;
typedef boost::shared_ptr< ::dishwasher_action::DishwasherFeedback const> DishwasherFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dishwasher_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'dishwasher_action': ['/home/koa/Desktop/ConcordiaRobotics/robotics-prototype/robot/demos/RosAction/devel/share/dishwasher_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c37c696f36e940481992cb4ade35617";
  }

  static const char* value(const ::dishwasher_action::DishwasherFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c37c696f36e9404ULL;
  static const uint64_t static_value2 = 0x81992cb4ade35617ULL;
};

template<class ContainerAllocator>
struct DataType< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dishwasher_action/DishwasherFeedback";
  }

  static const char* value(const ::dishwasher_action::DishwasherFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback definition\n\
float32 percentComplete\n\
\n\
";
  }

  static const char* value(const ::dishwasher_action::DishwasherFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentComplete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DishwasherFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dishwasher_action::DishwasherFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dishwasher_action::DishwasherFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentComplete: ";
    Printer<float>::stream(s, indent + "  ", v.percentComplete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISHWASHER_ACTION_MESSAGE_DISHWASHERFEEDBACK_H
