pinMode(M1_STEP_PIN,   OUTPUT);
pinMode(M1_DIR_PIN,    OUTPUT);
pinMode(M2_STEP_PIN,   OUTPUT);
pinMode(M2_DIR_PIN,    OUTPUT);
pinMode(SERVO_PIN,   OUTPUT);
pinMode(ENCODER_A, INPUT);
pinMode(ENCODER_B, INPUT);
pinMode(DC_PWM_PIN, OUTPUT);
pinMode(LED_PIN, OUTPUT);
