#include <Arduino.h>
#include "PinSetup.h"

void pinSetup(void){
	pinMode(HEARTBEAT_PIN, OUTPUT);

	pinMode(M1_ENABLE_PIN, OUTPUT);
	pinMode(M1_DIR_PIN, OUTPUT);
	pinMode(M1_STEP_PIN, OUTPUT);
	pinMode(M1_ENCODER_A, INPUT_PULLUP);
	pinMode(M1_ENCODER_B, INPUT_PULLUP);
	pinMode(M1_LIMIT_SW_CW, INPUT_PULLUP);
	pinMode(M1_LIMIT_SW_CCW, INPUT_PULLUP);

	pinMode(M3_ENABLE_PIN, OUTPUT);
	pinMode(M3_DIR_PIN, OUTPUT);
	pinMode(M3_STEP_PIN, OUTPUT);
	pinMode(M3_ENCODER_A, INPUT_PULLUP);
	pinMode(M3_ENCODER_B, INPUT_PULLUP);
	pinMode(M3_LIMIT_SW_FLEX, INPUT_PULLUP);
	pinMode(M3_LIMIT_SW_EXTEND, INPUT_PULLUP);

	pinMode(M4_ENABLE_PIN, OUTPUT);
	pinMode(M4_DIR_PIN, OUTPUT);
	pinMode(M4_STEP_PIN, OUTPUT);
	pinMode(M4_ENCODER_A, INPUT_PULLUP);
	pinMode(M4_ENCODER_B, INPUT_PULLUP);
	pinMode(M4_LIMIT_SW_FLEX, INPUT_PULLUP);
	pinMode(M4_LIMIT_SW_EXTEND, INPUT_PULLUP);

	// DC motor

	pinMode(M2_PWM_PIN, OUTPUT);
	/*pinMode(M2_UART_TX, OUTPUT);
	pinMode(M2_UART_RX, INPUT);*/
	pinMode(M2_ENCODER_A, INPUT_PULLUP);
	pinMode(M2_ENCODER_B, INPUT_PULLUP);
	pinMode(M2_LIMIT_SW_FLEX, INPUT_PULLUP);
	pinMode(M2_LIMIT_SW_EXTEND, INPUT_PULLUP);

	// servos

	pinMode(M5_PWM_PIN, OUTPUT);
	pinMode(M5_ENCODER_A, INPUT_PULLUP);
	pinMode(M5_ENCODER_B, INPUT_PULLUP);
	
	pinMode(M6_PWM_PIN, OUTPUT);
	pinMode(M6_ENCODER_A, INPUT_PULLUP);
	pinMode(M6_ENCODER_B, INPUT_PULLUP);
}
