// Generated by gencpp from file arm_control/ArmRequestResponse.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_ARMREQUESTRESPONSE_H
#define ARM_CONTROL_MESSAGE_ARMREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct ArmRequestResponse_
{
  typedef ArmRequestResponse_<ContainerAllocator> Type;

  ArmRequestResponse_()
    : response()
    , success(false)  {
    }
  ArmRequestResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::arm_control::ArmRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::ArmRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArmRequestResponse_

typedef ::arm_control::ArmRequestResponse_<std::allocator<void> > ArmRequestResponse;

typedef boost::shared_ptr< ::arm_control::ArmRequestResponse > ArmRequestResponsePtr;
typedef boost::shared_ptr< ::arm_control::ArmRequestResponse const> ArmRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::ArmRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::ArmRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'HasHeader': False, 'IsMessage': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arm_control': ['/home/vashmata/Programming/git/robotics-prototype/robot/rospackages/src/arm_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::ArmRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::ArmRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::ArmRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61c3bd4caa84e668cf48da398a910dc7";
  }

  static const char* value(const ::arm_control::ArmRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61c3bd4caa84e668ULL;
  static const uint64_t static_value2 = 0xcf48da398a910dc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/ArmRequestResponse";
  }

  static const char* value(const ::arm_control::ArmRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n\
bool success\n\
\n\
";
  }

  static const char* value(const ::arm_control::ArmRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::ArmRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::ArmRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_ARMREQUESTRESPONSE_H
