// Generated by gencpp from file arm_control/IkCommand.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_IKCOMMAND_H
#define ARM_CONTROL_MESSAGE_IKCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct IkCommand_
{
  typedef IkCommand_<ContainerAllocator> Type;

  IkCommand_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , wrist(0.0)  {
    }
  IkCommand_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , wrist(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _wrist_type;
  _wrist_type wrist;





  typedef boost::shared_ptr< ::arm_control::IkCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::IkCommand_<ContainerAllocator> const> ConstPtr;

}; // struct IkCommand_

typedef ::arm_control::IkCommand_<std::allocator<void> > IkCommand;

typedef boost::shared_ptr< ::arm_control::IkCommand > IkCommandPtr;
typedef boost::shared_ptr< ::arm_control::IkCommand const> IkCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::IkCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::IkCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'HasHeader': False, 'IsMessage': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'arm_control': ['/home/vashmata/Programming/git/robotics-prototype/robot/rospackages/src/arm_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::IkCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::IkCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::IkCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::IkCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::IkCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::IkCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::IkCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e56be75fc62b9fcc4a14e93c7d5229e8";
  }

  static const char* value(const ::arm_control::IkCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe56be75fc62b9fccULL;
  static const uint64_t static_value2 = 0x4a14e93c7d5229e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::IkCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/IkCommand";
  }

  static const char* value(const ::arm_control::IkCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::IkCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 wrist\n\
";
  }

  static const char* value(const ::arm_control::IkCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::IkCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.wrist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IkCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::IkCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::IkCommand_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "wrist: ";
    Printer<double>::stream(s, indent + "  ", v.wrist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_IKCOMMAND_H
