// Generated by gencpp from file arm_control/RoverPosition.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_ROVERPOSITION_H
#define ARM_CONTROL_MESSAGE_ROVERPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct RoverPosition_
{
  typedef RoverPosition_<ContainerAllocator> Type;

  RoverPosition_()
    : latitude(0.0)
    , longitude(0.0)
    , heading(0.0)  {
    }
  RoverPosition_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::arm_control::RoverPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::RoverPosition_<ContainerAllocator> const> ConstPtr;

}; // struct RoverPosition_

typedef ::arm_control::RoverPosition_<std::allocator<void> > RoverPosition;

typedef boost::shared_ptr< ::arm_control::RoverPosition > RoverPositionPtr;
typedef boost::shared_ptr< ::arm_control::RoverPosition const> RoverPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::RoverPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::RoverPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'HasHeader': False, 'IsMessage': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arm_control': ['/home/vashmata/Programming/git/robotics-prototype/robot/rospackages/src/arm_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::RoverPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::RoverPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::RoverPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::RoverPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::RoverPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::RoverPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::RoverPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a3396cc67514b0f3740edca07960ab1";
  }

  static const char* value(const ::arm_control::RoverPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a3396cc67514b0fULL;
  static const uint64_t static_value2 = 0x3740edca07960ab1ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::RoverPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/RoverPosition";
  }

  static const char* value(const ::arm_control::RoverPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::RoverPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n\
float64 longitude\n\
float64 heading\n\
";
  }

  static const char* value(const ::arm_control::RoverPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::RoverPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoverPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::RoverPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::RoverPosition_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_ROVERPOSITION_H
