// Generated by gencpp from file arm_control/ScienceRequest.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_SCIENCEREQUEST_H
#define ARM_CONTROL_MESSAGE_SCIENCEREQUEST_H

#include <ros/service_traits.h>


#include <arm_control/ScienceRequestRequest.h>
#include <arm_control/ScienceRequestResponse.h>


namespace arm_control
{

struct ScienceRequest
{

typedef ScienceRequestRequest Request;
typedef ScienceRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScienceRequest
} // namespace arm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_control::ScienceRequest > {
  static const char* value()
  {
    return "694b24ecd6b00b470b19b9b137151d30";
  }

  static const char* value(const ::arm_control::ScienceRequest&) { return value(); }
};

template<>
struct DataType< ::arm_control::ScienceRequest > {
  static const char* value()
  {
    return "arm_control/ScienceRequest";
  }

  static const char* value(const ::arm_control::ScienceRequest&) { return value(); }
};


// service_traits::MD5Sum< ::arm_control::ScienceRequestRequest> should match 
// service_traits::MD5Sum< ::arm_control::ScienceRequest > 
template<>
struct MD5Sum< ::arm_control::ScienceRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control::ScienceRequest >::value();
  }
  static const char* value(const ::arm_control::ScienceRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control::ScienceRequestRequest> should match 
// service_traits::DataType< ::arm_control::ScienceRequest > 
template<>
struct DataType< ::arm_control::ScienceRequestRequest>
{
  static const char* value()
  {
    return DataType< ::arm_control::ScienceRequest >::value();
  }
  static const char* value(const ::arm_control::ScienceRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_control::ScienceRequestResponse> should match 
// service_traits::MD5Sum< ::arm_control::ScienceRequest > 
template<>
struct MD5Sum< ::arm_control::ScienceRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_control::ScienceRequest >::value();
  }
  static const char* value(const ::arm_control::ScienceRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_control::ScienceRequestResponse> should match 
// service_traits::DataType< ::arm_control::ScienceRequest > 
template<>
struct DataType< ::arm_control::ScienceRequestResponse>
{
  static const char* value()
  {
    return DataType< ::arm_control::ScienceRequest >::value();
  }
  static const char* value(const ::arm_control::ScienceRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_SCIENCEREQUEST_H
