os: linux
dist: xenial
language: python
before_install:
    # Taken from this tutorial https://github.com/newdigate/teensy-blink
  - export ARDUINO_IDE_VERSION="1.8.12"
  - export ARDUINO_PATH="$HOME/arduino-$ARDUINO_IDE_VERSION" # Required for CMake script
  - export TEENSYDUINO_VERSION="152"
  - mkdir -p robot/rover/build
  - mkdir -p ~/Arduino/libraries
  - wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C /home/$USER/
  - curl -fsSL https://www.pjrc.com/teensy/td_$TEENSYDUINO_VERSION/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
  - chmod +x TeensyduinoInstall.linux64
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - ./TeensyduinoInstall.linux64 --dir=$ARDUINO_PATH
install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install -e .
  - python setup.py develop
script:
  - cd robot/rover/build
  - cmake ..
  - make
  - cd ../../..
  - pytest --continue-on-collection-errors
notifications:
  email:
    recipients:
      - cedricmartens98@gmail.com
      - william.wells@spaceconcordia.ca
      - tim.freiman@spaceconcordia.ca
      - peter.granitski@spaceconcordia.ca
      - joshua.glazer@spaceconcordia.ca
    on_success: change
    on_failure: change

python:
  #- "2.7" # not supported
  - "3.6"

# bypass submodules because gitlab requires authentication for pull
git:
  submodules: false
