// Auto-generated. Do not edit!

// (in-package dishwasher_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DishwasherGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dirtyDishes = null;
    }
    else {
      if (initObj.hasOwnProperty('dirtyDishes')) {
        this.dirtyDishes = initObj.dirtyDishes
      }
      else {
        this.dirtyDishes = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DishwasherGoal
    // Serialize message field [dirtyDishes]
    bufferOffset = _serializer.int32(obj.dirtyDishes, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DishwasherGoal
    let len;
    let data = new DishwasherGoal(null);
    // Deserialize message field [dirtyDishes]
    data.dirtyDishes = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dishwasher_action/DishwasherGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '11b004445e03767b789ca06b8b13193d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 dirtyDishes
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DishwasherGoal(null);
    if (msg.dirtyDishes !== undefined) {
      resolved.dirtyDishes = msg.dirtyDishes;
    }
    else {
      resolved.dirtyDishes = 0
    }

    return resolved;
    }
};

module.exports = DishwasherGoal;
