// Auto-generated. Do not edit!

// (in-package dishwasher_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DishwasherResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dishesWashed = null;
    }
    else {
      if (initObj.hasOwnProperty('dishesWashed')) {
        this.dishesWashed = initObj.dishesWashed
      }
      else {
        this.dishesWashed = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DishwasherResult
    // Serialize message field [dishesWashed]
    bufferOffset = _serializer.string(obj.dishesWashed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DishwasherResult
    let len;
    let data = new DishwasherResult(null);
    // Deserialize message field [dishesWashed]
    data.dishesWashed = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.dishesWashed.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dishwasher_action/DishwasherResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3f0b089f3078e2af93fb747be1fd2495';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    string dishesWashed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DishwasherResult(null);
    if (msg.dishesWashed !== undefined) {
      resolved.dishesWashed = msg.dishesWashed;
    }
    else {
      resolved.dishesWashed = ''
    }

    return resolved;
    }
};

module.exports = DishwasherResult;
