// Auto-generated. Do not edit!

// (in-package dishwasher_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DishwasherFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percentComplete = null;
    }
    else {
      if (initObj.hasOwnProperty('percentComplete')) {
        this.percentComplete = initObj.percentComplete
      }
      else {
        this.percentComplete = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DishwasherFeedback
    // Serialize message field [percentComplete]
    bufferOffset = _serializer.float32(obj.percentComplete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DishwasherFeedback
    let len;
    let data = new DishwasherFeedback(null);
    // Deserialize message field [percentComplete]
    data.percentComplete = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dishwasher_action/DishwasherFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9c37c696f36e940481992cb4ade35617';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback definition
    float32 percentComplete
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DishwasherFeedback(null);
    if (msg.percentComplete !== undefined) {
      resolved.percentComplete = msg.percentComplete;
    }
    else {
      resolved.percentComplete = 0.0
    }

    return resolved;
    }
};

module.exports = DishwasherFeedback;
