; Auto-generated. Do not edit!


(cl:in-package dishwasher_action-msg)


;//! \htmlinclude DishwasherFeedback.msg.html

(cl:defclass <DishwasherFeedback> (roslisp-msg-protocol:ros-message)
  ((percentComplete
    :reader percentComplete
    :initarg :percentComplete
    :type cl:float
    :initform 0.0))
)

(cl:defclass DishwasherFeedback (<DishwasherFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DishwasherFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DishwasherFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dishwasher_action-msg:<DishwasherFeedback> is deprecated: use dishwasher_action-msg:DishwasherFeedback instead.")))

(cl:ensure-generic-function 'percentComplete-val :lambda-list '(m))
(cl:defmethod percentComplete-val ((m <DishwasherFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dishwasher_action-msg:percentComplete-val is deprecated.  Use dishwasher_action-msg:percentComplete instead.")
  (percentComplete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DishwasherFeedback>) ostream)
  "Serializes a message object of type '<DishwasherFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percentComplete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DishwasherFeedback>) istream)
  "Deserializes a message object of type '<DishwasherFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentComplete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DishwasherFeedback>)))
  "Returns string type for a message object of type '<DishwasherFeedback>"
  "dishwasher_action/DishwasherFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DishwasherFeedback)))
  "Returns string type for a message object of type 'DishwasherFeedback"
  "dishwasher_action/DishwasherFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DishwasherFeedback>)))
  "Returns md5sum for a message object of type '<DishwasherFeedback>"
  "9c37c696f36e940481992cb4ade35617")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DishwasherFeedback)))
  "Returns md5sum for a message object of type 'DishwasherFeedback"
  "9c37c696f36e940481992cb4ade35617")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DishwasherFeedback>)))
  "Returns full string definition for message of type '<DishwasherFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%float32 percentComplete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DishwasherFeedback)))
  "Returns full string definition for message of type 'DishwasherFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%float32 percentComplete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DishwasherFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DishwasherFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DishwasherFeedback
    (cl:cons ':percentComplete (percentComplete msg))
))
