; Auto-generated. Do not edit!


(cl:in-package dishwasher_action-msg)


;//! \htmlinclude DishwasherResult.msg.html

(cl:defclass <DishwasherResult> (roslisp-msg-protocol:ros-message)
  ((dishesWashed
    :reader dishesWashed
    :initarg :dishesWashed
    :type cl:string
    :initform ""))
)

(cl:defclass DishwasherResult (<DishwasherResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DishwasherResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DishwasherResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dishwasher_action-msg:<DishwasherResult> is deprecated: use dishwasher_action-msg:DishwasherResult instead.")))

(cl:ensure-generic-function 'dishesWashed-val :lambda-list '(m))
(cl:defmethod dishesWashed-val ((m <DishwasherResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dishwasher_action-msg:dishesWashed-val is deprecated.  Use dishwasher_action-msg:dishesWashed instead.")
  (dishesWashed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DishwasherResult>) ostream)
  "Serializes a message object of type '<DishwasherResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'dishesWashed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'dishesWashed))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DishwasherResult>) istream)
  "Deserializes a message object of type '<DishwasherResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dishesWashed) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'dishesWashed) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DishwasherResult>)))
  "Returns string type for a message object of type '<DishwasherResult>"
  "dishwasher_action/DishwasherResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DishwasherResult)))
  "Returns string type for a message object of type 'DishwasherResult"
  "dishwasher_action/DishwasherResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DishwasherResult>)))
  "Returns md5sum for a message object of type '<DishwasherResult>"
  "3f0b089f3078e2af93fb747be1fd2495")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DishwasherResult)))
  "Returns md5sum for a message object of type 'DishwasherResult"
  "3f0b089f3078e2af93fb747be1fd2495")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DishwasherResult>)))
  "Returns full string definition for message of type '<DishwasherResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string dishesWashed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DishwasherResult)))
  "Returns full string definition for message of type 'DishwasherResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string dishesWashed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DishwasherResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'dishesWashed))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DishwasherResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DishwasherResult
    (cl:cons ':dishesWashed (dishesWashed msg))
))
