// Generated by gencpp from file serial_cmd/SerialCmd.msg
// DO NOT EDIT!


#ifndef SERIAL_CMD_MESSAGE_SERIALCMD_H
#define SERIAL_CMD_MESSAGE_SERIALCMD_H

#include <ros/service_traits.h>


#include <serial_cmd/SerialCmdRequest.h>
#include <serial_cmd/SerialCmdResponse.h>


namespace serial_cmd
{

struct SerialCmd
{

typedef SerialCmdRequest Request;
typedef SerialCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialCmd
} // namespace serial_cmd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_cmd::SerialCmd > {
  static const char* value()
  {
    return "44a43a3c9ed832dd024eb4e68053d686";
  }

  static const char* value(const ::serial_cmd::SerialCmd&) { return value(); }
};

template<>
struct DataType< ::serial_cmd::SerialCmd > {
  static const char* value()
  {
    return "serial_cmd/SerialCmd";
  }

  static const char* value(const ::serial_cmd::SerialCmd&) { return value(); }
};


// service_traits::MD5Sum< ::serial_cmd::SerialCmdRequest> should match 
// service_traits::MD5Sum< ::serial_cmd::SerialCmd > 
template<>
struct MD5Sum< ::serial_cmd::SerialCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_cmd::SerialCmd >::value();
  }
  static const char* value(const ::serial_cmd::SerialCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_cmd::SerialCmdRequest> should match 
// service_traits::DataType< ::serial_cmd::SerialCmd > 
template<>
struct DataType< ::serial_cmd::SerialCmdRequest>
{
  static const char* value()
  {
    return DataType< ::serial_cmd::SerialCmd >::value();
  }
  static const char* value(const ::serial_cmd::SerialCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_cmd::SerialCmdResponse> should match 
// service_traits::MD5Sum< ::serial_cmd::SerialCmd > 
template<>
struct MD5Sum< ::serial_cmd::SerialCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_cmd::SerialCmd >::value();
  }
  static const char* value(const ::serial_cmd::SerialCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_cmd::SerialCmdResponse> should match 
// service_traits::DataType< ::serial_cmd::SerialCmd > 
template<>
struct DataType< ::serial_cmd::SerialCmdResponse>
{
  static const char* value()
  {
    return DataType< ::serial_cmd::SerialCmd >::value();
  }
  static const char* value(const ::serial_cmd::SerialCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_CMD_MESSAGE_SERIALCMD_H
