// Generated by gencpp from file ping_acknowledgment/PingResponse.msg
// DO NOT EDIT!


#ifndef PING_ACKNOWLEDGMENT_MESSAGE_PINGRESPONSE_H
#define PING_ACKNOWLEDGMENT_MESSAGE_PINGRESPONSE_H

#include <ros/service_traits.h>


#include <ping_acknowledgment/PingResponseRequest.h>
#include <ping_acknowledgment/PingResponseResponse.h>


namespace ping_acknowledgment
{

struct PingResponse
{

typedef PingResponseRequest Request;
typedef PingResponseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PingResponse
} // namespace ping_acknowledgment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ping_acknowledgment::PingResponse > {
  static const char* value()
  {
    return "2c33f5a2bff59c326ae8656e9ffa7758";
  }

  static const char* value(const ::ping_acknowledgment::PingResponse&) { return value(); }
};

template<>
struct DataType< ::ping_acknowledgment::PingResponse > {
  static const char* value()
  {
    return "ping_acknowledgment/PingResponse";
  }

  static const char* value(const ::ping_acknowledgment::PingResponse&) { return value(); }
};


// service_traits::MD5Sum< ::ping_acknowledgment::PingResponseRequest> should match 
// service_traits::MD5Sum< ::ping_acknowledgment::PingResponse > 
template<>
struct MD5Sum< ::ping_acknowledgment::PingResponseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ping_acknowledgment::PingResponse >::value();
  }
  static const char* value(const ::ping_acknowledgment::PingResponseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ping_acknowledgment::PingResponseRequest> should match 
// service_traits::DataType< ::ping_acknowledgment::PingResponse > 
template<>
struct DataType< ::ping_acknowledgment::PingResponseRequest>
{
  static const char* value()
  {
    return DataType< ::ping_acknowledgment::PingResponse >::value();
  }
  static const char* value(const ::ping_acknowledgment::PingResponseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ping_acknowledgment::PingResponseResponse> should match 
// service_traits::MD5Sum< ::ping_acknowledgment::PingResponse > 
template<>
struct MD5Sum< ::ping_acknowledgment::PingResponseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ping_acknowledgment::PingResponse >::value();
  }
  static const char* value(const ::ping_acknowledgment::PingResponseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ping_acknowledgment::PingResponseResponse> should match 
// service_traits::DataType< ::ping_acknowledgment::PingResponse > 
template<>
struct DataType< ::ping_acknowledgment::PingResponseResponse>
{
  static const char* value()
  {
    return DataType< ::ping_acknowledgment::PingResponse >::value();
  }
  static const char* value(const ::ping_acknowledgment::PingResponseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PING_ACKNOWLEDGMENT_MESSAGE_PINGRESPONSE_H
