// Generated by gencpp from file ping_acknowledgment/PingResponseRequest.msg
// DO NOT EDIT!


#ifndef PING_ACKNOWLEDGMENT_MESSAGE_PINGRESPONSEREQUEST_H
#define PING_ACKNOWLEDGMENT_MESSAGE_PINGRESPONSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ping_acknowledgment
{
template <class ContainerAllocator>
struct PingResponseRequest_
{
  typedef PingResponseRequest_<ContainerAllocator> Type;

  PingResponseRequest_()
    : ping()  {
    }
  PingResponseRequest_(const ContainerAllocator& _alloc)
    : ping(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ping_type;
  _ping_type ping;





  typedef boost::shared_ptr< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PingResponseRequest_

typedef ::ping_acknowledgment::PingResponseRequest_<std::allocator<void> > PingResponseRequest;

typedef boost::shared_ptr< ::ping_acknowledgment::PingResponseRequest > PingResponseRequestPtr;
typedef boost::shared_ptr< ::ping_acknowledgment::PingResponseRequest const> PingResponseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ping_acknowledgment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8f8c3756a1817228220197729a1b95e";
  }

  static const char* value(const ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8f8c3756a181722ULL;
  static const uint64_t static_value2 = 0x8220197729a1b95eULL;
};

template<class ContainerAllocator>
struct DataType< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ping_acknowledgment/PingResponseRequest";
  }

  static const char* value(const ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ping\n\
";
  }

  static const char* value(const ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ping);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PingResponseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ping_acknowledgment::PingResponseRequest_<ContainerAllocator>& v)
  {
    s << indent << "ping: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ping);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PING_ACKNOWLEDGMENT_MESSAGE_PINGRESPONSEREQUEST_H
