# GPS WPF CHANGE: Remove static layer
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 100.0
      publish_frequency: 100.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      footprint: "[[0.7,0.4],[0.7,-0.4],[-0.7,-0.4],[-0.7,0.4]]"
      # robot_radius: 0.22
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          sensor_frame: os_lidar
          topic: /points
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      always_send_full_costmap: True

# GPS WPF CHANGE: Remove static layer
# GPS WPF CHANGE: Set rolling global costmap with 50x50 size. See note below
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 100.0
      publish_frequency: 100.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[[0.6,0.25],[0.6,-0.25],[-0.6,-0.25],[-0.6,0.25]]"
      resolution: 0.1
      # When using GPS navigation you will potentially traverse huge environments which are not practical to
      # fit on a big static costmap. Thus it is recommended to use a rolling global costmap large enough to 
      # contain each pair of successive waypoints. See: https://github.com/ros-planning/navigation2/issues/2174
      rolling_window: True
      width: 500
      height: 500
      track_unknown_space: false
      # no static map
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud scan
        pointcloud:
          sensor_frame: os_lidar
          topic: /points
          footprint_clearing_enabled: true
          max_obstacle_height: 2.0
          min_obstacle_height: 0.25
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 50.0
          obstacle_min_range: 0.0
          #outdoors there will probably be more inf points
          # inf_is_valid: true
        scan:
          sensor_frame: os_lidar
          topic: /scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.25
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 90.0
          raytrace_min_range: 0.0
          obstacle_max_range: 50.0
          obstacle_min_range: 0.0
          #outdoors there will probably be more inf points
          inf_is_valid: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True

