// Generated by gencpp from file mcu_control/ScienceRequest.msg
// DO NOT EDIT!


#ifndef MCU_CONTROL_MESSAGE_SCIENCEREQUEST_H
#define MCU_CONTROL_MESSAGE_SCIENCEREQUEST_H

#include <ros/service_traits.h>


#include <mcu_control/ScienceRequestRequest.h>
#include <mcu_control/ScienceRequestResponse.h>


namespace mcu_control
{

struct ScienceRequest
{

typedef ScienceRequestRequest Request;
typedef ScienceRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScienceRequest
} // namespace mcu_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcu_control::ScienceRequest > {
  static const char* value()
  {
    return "694b24ecd6b00b470b19b9b137151d30";
  }

  static const char* value(const ::mcu_control::ScienceRequest&) { return value(); }
};

template<>
struct DataType< ::mcu_control::ScienceRequest > {
  static const char* value()
  {
    return "mcu_control/ScienceRequest";
  }

  static const char* value(const ::mcu_control::ScienceRequest&) { return value(); }
};


// service_traits::MD5Sum< ::mcu_control::ScienceRequestRequest> should match 
// service_traits::MD5Sum< ::mcu_control::ScienceRequest > 
template<>
struct MD5Sum< ::mcu_control::ScienceRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcu_control::ScienceRequest >::value();
  }
  static const char* value(const ::mcu_control::ScienceRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcu_control::ScienceRequestRequest> should match 
// service_traits::DataType< ::mcu_control::ScienceRequest > 
template<>
struct DataType< ::mcu_control::ScienceRequestRequest>
{
  static const char* value()
  {
    return DataType< ::mcu_control::ScienceRequest >::value();
  }
  static const char* value(const ::mcu_control::ScienceRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcu_control::ScienceRequestResponse> should match 
// service_traits::MD5Sum< ::mcu_control::ScienceRequest > 
template<>
struct MD5Sum< ::mcu_control::ScienceRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcu_control::ScienceRequest >::value();
  }
  static const char* value(const ::mcu_control::ScienceRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcu_control::ScienceRequestResponse> should match 
// service_traits::DataType< ::mcu_control::ScienceRequest > 
template<>
struct DataType< ::mcu_control::ScienceRequestResponse>
{
  static const char* value()
  {
    return DataType< ::mcu_control::ScienceRequest >::value();
  }
  static const char* value(const ::mcu_control::ScienceRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCU_CONTROL_MESSAGE_SCIENCEREQUEST_H
