version: '3.6' # compatible with ubuntu bionic

services:
    ros-master:
        image: ros:melodic-ros-core
        command: stdbuf -o L roscore
        restart: always

    rosbridge:
        build: ./rosbridge 
        depends_on:
            - ros-master
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"
        ports:
            - "9090:9090"
    prototype:
        build: ..
        depends_on:
            - ros-master
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"

        ports:
            - "5000:5000"
