version: '3.6' # compatible with ubuntu bionic

networks:
    rp-network:
        driver: bridge

services:
    ros-master:
        image: ros:melodic-ros-core
        command: stdbuf -o L roscore
        restart: always
        networks:
            - rp-network

    rosbridge:
        build:
            context: ../
            dockerfile: ./docker/rosbridge/Dockerfile
        depends_on:
            - ros-master
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"
        ports:
            - "9090:9090"
        restart: always
        networks:
            - rp-network
    prototype:
        build: ..
        depends_on:
            - ros-master
            - rosbridge
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"

        ports:
            - "5000:5000"
        restart: always
        networks:
            - rp-network
