enable_button: 5
stop_command: "stop_motors"
command_topic: /arm_command
controller_mappings: [["BUTTON_CROSS", "set_motor_speeds 250 0 0 0 0 0", 30],
                      ["BUTTON_SQUARE", "set_motor_speeds -250 0 0 0 0 0", 30],

                      [ "BUTTON_TRIANGLE", "set_motor_speeds 0 250 0 0 0 0", 30 ],
                      [ "BUTTON_CIRCLE", "set_motor_speeds 0 -250 0 0 0 0", 30 ],

                      [ "BUTTON_DPAD_DOWN", "set_motor_speeds 0 0 250 0 0 0", 30 ],
                      [ "BUTTON_DPAD_LEFT", "set_motor_speeds 0 0 -250 0 0 0", 30 ],

                      [ "BUTTON_DPAD_RIGHT", "set_motor_speeds 0 0 0 250 0 0", 30 ],
                      [ "BUTTON_DPAD_UP", "set_motor_speeds 0 0 0 -250 0 0", 30 ],

                      [ "BUTTON_SHARE", "set_motor_speeds 0 0 0 0 250 0", 30 ],
                      [ "BUTTON_OPTION", "set_motor_speeds 0 0 0 0 -250 0", 30 ],

                      [ "BUTTON_R2", "set_motor_speeds 0 0 0 0 0 250", 30 ],
                      [ "BUTTON_L2", "set_motor_speeds 0 0 0 0 0 -250", 30 ],

                      [ "BUTTON_R3", "arm_speed 5", 30 ],
                      [ "BUTTON_L3", "arm_speed 1", 30 ],

                      [ "BUTTON_HOME", "reboot", 30 ]]

