enable_button: 5
#number of commands has to match the number of mappings in controller_mappings and topics in command_topics
stop_commands: 
  - "motors_stop"
  - "motors_estop"
#number of topics has to match the number of mappings in controller_mappings and commands in stop_commands
command_topics: 
  - /arm_command
  - /rover_command
#number of mappings has to match the number of topics in command_topics and commands in stop_commands
controller_mappings:
# D pad left
  - - ["BUTTON_CROSS","budge_motors 0 0 0 0 1 0",50]
    - ["BUTTON_TRIANGLE","budge_motors 0 0 0 0 -1 0",10]
    - ["BUTTON_CIRCLE","budge_motors 0 0 0 0 0 1",10]
    - ["BUTTON_SQUARE","budge_motors 0 0 0 0 0 -1",10]
    - ["JOY_LEFT_X","budge_motors %b 0 0 0 0 0",10]
    - ["JOY_LEFT_Y","budge_motors 0 %b 0 0 0 0",10]
    - ["JOY_RIGHT_X","budge_motors 0 0 %b 0 0 0",10]
    - ["JOY_RIGHT_Y","budge_motors 0 0 0 %b 0 0",10]
# D pad up
  - - ["JOY_LEFT_X","move_wheels 0 0 %a",10]
    - ["JOY_LEFT_Y","move_wheels 0 1 %a",10]
    - ["JOY_RIGHT_X","move_wheels 1 0 %a",10]
    - ["JOY_RIGHT_Y","move_wheels 1 1 %a",10]
# D pad right
# D pad down