enable_button: 5
stop_command: "stop_motors"
command_topic: /rover_command
controller_mappings: [[ "BUTTON_L2", "move_wheels 0 0 80", "BUTTON_DPAD_UP", "move_wheels 0 1 200" ],
                      [ "BUTTON_L2", "move_wheels 0 0 150", "BUTTON_DPAD_UP", "move_wheels 0 1 200" ],
                      [ "BUTTON_L2", "move_wheels 0 0 200", "BUTTON_DPAD_UP", "move_wheels 0 1 200" ],

                      [ "BUTTON_R2", "move_wheels 0 0 80", "BUTTON_TRIANGLE", "move_wheels 0 1 200" ],
                      [ "BUTTON_R2", "move_wheels 0 0 150", "BUTTON_TRIANGLE", "move_wheels 0 1 200" ],
                      [ "BUTTON_R2", "move_wheels 0 0 200", "BUTTON_TRIANGLE", "move_wheels 0 1 200" ]]

