(cl:defpackage arm_control-srv
  (:use )
  (:export
   "ARMREQUEST"
   "<ARMREQUEST-REQUEST>"
   "ARMREQUEST-REQUEST"
   "<ARMREQUEST-RESPONSE>"
   "ARMREQUEST-RESPONSE"
   "SCIENCEREQUEST"
   "<SCIENCEREQUEST-REQUEST>"
   "SCIENCEREQUEST-REQUEST"
   "<SCIENCEREQUEST-RESPONSE>"
   "SCIENCEREQUEST-RESPONSE"
  ))

