// Generated by gencpp from file mux_selector/SelectMuxRequest.msg
// DO NOT EDIT!


#ifndef MUX_SELECTOR_MESSAGE_SELECTMUXREQUEST_H
#define MUX_SELECTOR_MESSAGE_SELECTMUXREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mux_selector
{
template <class ContainerAllocator>
struct SelectMuxRequest_
{
  typedef SelectMuxRequest_<ContainerAllocator> Type;

  SelectMuxRequest_()
    : device()  {
    }
  SelectMuxRequest_(const ContainerAllocator& _alloc)
    : device(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _device_type;
  _device_type device;





  typedef boost::shared_ptr< ::mux_selector::SelectMuxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mux_selector::SelectMuxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SelectMuxRequest_

typedef ::mux_selector::SelectMuxRequest_<std::allocator<void> > SelectMuxRequest;

typedef boost::shared_ptr< ::mux_selector::SelectMuxRequest > SelectMuxRequestPtr;
typedef boost::shared_ptr< ::mux_selector::SelectMuxRequest const> SelectMuxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mux_selector::SelectMuxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mux_selector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mux_selector::SelectMuxRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mux_selector::SelectMuxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mux_selector::SelectMuxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b143d1069c7861320973824c82b9d8";
  }

  static const char* value(const ::mux_selector::SelectMuxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b143d1069c7861ULL;
  static const uint64_t static_value2 = 0x320973824c82b9d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mux_selector/SelectMuxRequest";
  }

  static const char* value(const ::mux_selector::SelectMuxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string device\n\
";
  }

  static const char* value(const ::mux_selector::SelectMuxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelectMuxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mux_selector::SelectMuxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mux_selector::SelectMuxRequest_<ContainerAllocator>& v)
  {
    s << indent << "device: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.device);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUX_SELECTOR_MESSAGE_SELECTMUXREQUEST_H
