site_name: usb_cam Documentation
site_url: https://ros-drivers.github.io/usb_cam/
site_author: Evan Flynn
repo_url: https://github.com/ros-drivers/usb_cam.git
theme:
  name: 'material'
  features:
    - navigation.indexes
    - navigation.tracking
plugins:
  - search
  - awesome-pages
extra:
  version:
    provider: mike
