name: ROS CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:

      - name: Setup Environment
        run: robotics-prototyp/.github/workflows/environment.sh

      - name: Install arduino compiler
        run: robotics-prototyp/.github/workflows/teensyduino.sh

      - name: Run pytest
        run: |
          cd robotics-prototype && pytest
