name: ROS CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:

      - name: Clone branch
        env: 
          SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          git config credential.helper store
          echo "https://https://$SECRET@github.com/space-concordia-robotics/autonomy-packages > ~/.git-credentials"
          git clone --recursive -b gh-actions-493 https://$SECRET@github.com/space-concordia-robotics/robotics-prototype ~/robotics-prototype

      - name: Setup Environment
        run: |
          cd ~/robotics-prototype
          ./.github/workflows/environment.sh

      - name: Configure ROS environment
        run: |
          cd ~/robotics-prototype
          ./.github/workflows/ros.sh

      - name: Install arduino compiler
        run: |
          cd ~/robotics-prototype
          ./.github/workflows/teensyduino.sh


      - name: Run pytest
        run: |
          cd ~/robotics-prototype 
          bash -c "source venv/bin/activate && pytest"
