name: ROS CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:

      - name: Clone branch without autonomy module
        run: git clone --recursive -b gh-actions-493 https://github.com/space-concordia-robotics/robotics-prototype ~/

      - name:
        run: |
          cd $HOME
          ls
      #- name: Setup Environment
        #run: robotics-prototype/.github/workflows/environment.sh

      #- name: Install arduino compiler
        #run: robotics-prototype/.github/workflows/teensyduino.sh

      #- name: Run pytest
        #run: |
          #cd robotics-prototype && pytest
