name: ROS CI

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base
    steps:

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          ./.github/workflows/environment.sh

      - name: Configure ROS environment
        run: |
          ./scripts/ros_install.sh

      - name: Install teensyduino and run cmake on codebase
        run: |
          ./scripts/OLD_install-arduino_teensyduino.sh


          #      - name: Run pytest
          #        run: |
          #          bash -c "source venv/bin/activate && source robot/rospackages/devel/setup.bash && pytest"
