name: ROS CI

on:
  pull_request:
    branches: 
    - master
  push:  
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          ./environment.sh

      - name: Configure ROS environment
        run: |
          ./ros.sh

      - name: Install teensyduino and run cmake on codebase
        run: |
          cd ~/robotics-prototype
          ./teensyduino.sh

      - name: Run pytest
        run: |
          bash -c "source venv/bin/activate && source robot/rospackages/devel/setup.bash && pytest"
