name: ROS CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:
      # Use github workspace so that job can access repo
      #
      #
      #
      #

      - name: Run some commands to find out what is up with the container
        run: |
          rosversion
          python --version
          echo $HOME
          pwd




      #- name: Clone Repo
        #run : git clone --recursive -b gh-actions-493 https://github.com/space-concordia-robotics/robotics-prototype/ ~/Programming/robotics-prototype

      #- name: Enter repo and run script
        #run: cd ~/Programming/robotics-prototype && ./EnvironmentSetup.sh

      #- name: Run pytest
        #run: pytest
