name: ROS CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:
      # Use github workspace so that job can access repo
      #
      #
      #
      #

      - name: Update the container
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Clone Repo (Without autonomy module for now)
        run : git clone --recursive -b gh-actions-493 https://github.com/space-concordia-robotics/robotics-prototype ~/Programming

      #- name: Enter repo and run script
        #run: cd ~/Programming/robotics-prototype && ./EnvironmentSetup.sh

      #- name: Run pytest
        #run: pytest
