APP_NAME := ScienceTests
ARDUINO_LIB_DIRS := ../../
ARDUINO_LIBS := AUnit science
include ../../../../../../Arduino/libraries/UnixHostDuino/UnixHostDuino.mk

ScienceTests.exe : ScienceTests.out
	./ScienceTests.out